edited readme
johnspeny/ProjectReviewMicroverse pull request #1
Opened 2021-07-09 16:45 UTC by johnspeny

- Add linter to your project 
- in your index.html use <br/> instead of <br>

2021-07-09 19:58 UTC, Dipeshtwis reviewed
# Status: Invalid ❌

While you made a great effort in this project, Unfortunately, I cannot proceed to review your code. Please fix the issue mentioned below and then request for code review

## Reason

- [ ] You have used PR description to review your project. Whereas to make a valid review you have to use a GitHub inline-comment.

### Please make sure to submit code review when you are done with the changes that was requested

**Don't worry you still have same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

**_Dipesh Kumar_**

2021-07-09 20:36 UTC, johnspeny reviewed
1.  Add social links to your readme file
2. Add steps that show how a user can run your application locally

2021-07-09 20:58 UTC, smcommits requested changes
H @johnspeny, 

### Nice work providing a review using comments. However, as requested by the previous reviewer, you have to use Github review features to provide a review. 
 ## Required Changes ♻️

Please use [this guide](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) to understand more about giving a code review. You have to follow the steps mentioned in the guide and submit a review. 

Please make sure to perform the following while you are giving a review. These are elaborated in the guide that is linked above.

- [ ] **Please make sure to use inline comments while giving a review**
- [ ] **Please make sure to use Github's `Review Changes` feature to submit a review**
- [ ] **Please make your comments more descriptive. If you are requesting any change, please elaborate a little on why is that change essential. How will help to improve the code or the repo? 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-10 10:55 UTC, johnspeny reviewed
# Changes required ♻️ 

Please check my comments below and make all required changes.

Submit for re-review when you're done.

Thanks 😃 .

2021-07-10 10:55 UTC, johnspeny commented on index.html
> -    <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
I think it is a good practice to place script tags meant for javascript just before the end of the body tag. In this way, it leaves your code clean and readable.

2021-07-10 10:55 UTC, johnspeny commented on css/style.css
> -
It would be very helpful and time saving if you used a tool called linter. It helps in early detection of css  and HTML flaws in code. In your case the extra lines in the css file would be detected early an removed. 👍

2021-07-10 10:55 UTC, johnspeny commented on README.md
> -You don't know how to fork a project? [Click hear](https://help.github.com/articles/fork-a-repo/) to learn how to do it.
Good job 🥇  with creating a readme for everyone to understand. Just a few more descriptions would help further. Add steps in which the user can set up your project on their local machine.

2021-07-10 11:01 UTC, smcommits approved these changes
### Status: Approved 👍🏽 

Hi @johnspeny, 

## You have done a great job! Your project is complete. This PR is now approved. You can go ahead and merge the branch. Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-10 11:02 UTC, merged